// Start SQA testing-plan document generation on the Repo Reader service.
// No files are uploaded: the service reuses the documents already generated by
// the project's completed repo/BRD job (<source_job_id>).
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "../_shared/cors.ts";

const BASE = (Deno.env.get("REPO_READER_BASE_URL_V1") || "https://reporeader.qualixa.cortanexai.com").replace(/\/+$/, "");
const API_KEY = Deno.env.get("REPO_READER_API_KEY_V1") || "qualixa-repo-reader-key";

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) return j({ error: "Unauthorized" }, 401);

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const { data: claims } = await supabase.auth.getClaims(authHeader.replace("Bearer ", ""));
    if (!claims?.claims) return j({ error: "Unauthorized" }, 401);
    const userId = claims.claims.sub as string;

    const { test_plan_id, model } = await req.json();
    if (!test_plan_id) return j({ error: "test_plan_id required" }, 400);

    // RLS-scoped read: the caller must be able to see the plan.
    const { data: plan } = await supabase
      .from("test_plans")
      .select("id, name, project_id, docs_status")
      .eq("id", test_plan_id)
      .maybeSingle();
    if (!plan) return j({ error: "Test plan not found" }, 404);
    if (plan.docs_status === "running" || plan.docs_status === "queued") {
      return j({ error: "Document generation is already running for this plan" }, 409);
    }
    if (!plan.project_id) return j({ error: "This test plan is not linked to a project" }, 400);

    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    const { data: project } = await admin
      .from("projects")
      .select("id, repo_job_id, repo_job_status")
      .eq("id", plan.project_id)
      .maybeSingle();

    const sourceJobId = project?.repo_job_id;
    if (!sourceJobId) {
      return j({ error: "The project has no completed source job yet — ingest a repository or BRD first." }, 400);
    }
    const srcStatus = String(project?.repo_job_status || "").toLowerCase();
    if (!["succeeded", "completed", "success", "ready"].includes(srcStatus)) {
      return j({ error: `The project's source job is not completed yet (status: ${srcStatus || "unknown"}).` }, 409);
    }

    const res = await fetch(`${BASE}/v1/jobs/${sourceJobId}/sqa-plan`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${API_KEY}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        model: model ?? null,
        metadata: { test_plan_id, project_id: plan.project_id, requested_by: userId },
        forward_to_test_doc: false,
      }),
    });
    const text = await res.text();
    if (!res.ok) {
      let detail = text.slice(0, 400);
      try { const p = JSON.parse(text); detail = p?.error || p?.detail || p?.message || detail; } catch { /* raw */ }
      if (res.status === 409) detail = "The source job is not completed yet.";
      if (res.status === 400) detail = "The source job has no readable generated documents.";
      return j({ error: `Repo Reader ${res.status}: ${detail}`, upstream_status: res.status }, res.status >= 500 ? 503 : res.status);
    }
    const data = JSON.parse(text || "{}");
    const jobId = data.id || data.job_id;

    await admin.from("test_plans").update({
      docs_status: "running",
      docs_job_ref: jobId,
      docs_source_job_ref: sourceJobId,
      docs_progress: 0,
      docs_progress_message: "SQA testing-plan job queued on Repo Reader",
      docs_progress_updated_at: new Date().toISOString(),
      docs_last_run_at: new Date().toISOString(),
    }).eq("id", test_plan_id);

    await admin.from("generation_stage_logs").insert({
      test_plan_id, kind: "docs", stage: "submit",
      message: `SQA plan job ${jobId} created from source job ${sourceJobId}`,
      created_by: userId,
    }).select().maybeSingle().catch?.(() => {});

    return j({ success: true, job_id: jobId, status: data.status || "queued", source_job_id: sourceJobId }, 202);
  } catch (e) {
    return j({ error: (e as Error).message }, 500);
  }
});

function j(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status, headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
