// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List Qualixa projects visible to the signed-in user, optionally filtered by workspace.",
  inputSchema: {
    workspace_id: z.string().uuid().optional().describe("Optional workspace UUID to filter by."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("projects").select("id, name, description, workspace_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (workspace_id) q = q.eq("workspace_id", workspace_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { projects: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-test-plans.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_test_plans_default = defineTool2({
  name: "list_test_plans",
  title: "List test plans",
  description: "List Qualixa test plans, optionally scoped to a project.",
  inputSchema: {
    project_id: z2.string().uuid().optional().describe("Optional project UUID to filter by."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("test_plans").select("id, name, description, project_id, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (project_id) q = q.eq("project_id", project_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { test_plans: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-test-cases.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_test_cases_default = defineTool3({
  name: "list_test_cases",
  title: "List test cases",
  description: "List Qualixa test cases, optionally scoped to a project.",
  inputSchema: {
    project_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb3(ctx).from("test_cases").select("id, title, description, project_id, priority, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (project_id) q = q.eq("project_id", project_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { test_cases: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-defects.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_defects_default = defineTool4({
  name: "list_defects",
  title: "List defects",
  description: "List Qualixa defects with optional project and status filters.",
  inputSchema: {
    project_id: z4.string().uuid().optional(),
    status: z4.string().optional().describe("Filter by status (e.g. open, closed, in_progress)."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb4(ctx).from("defects").select("id, title, status, severity, priority, project_id, assigned_to, reported_by, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (project_id) q = q.eq("project_id", project_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { defects: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-defect.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_defect_default = defineTool5({
  name: "create_defect",
  title: "Create defect",
  description: "File a new defect in a Qualixa project as the signed-in user.",
  inputSchema: {
    project_id: z5.string().uuid().describe("Project the defect belongs to."),
    title: z5.string().trim().min(1).describe("Short defect title."),
    description: z5.string().optional().describe("Detailed description / reproduction steps."),
    severity: z5.enum(["low", "medium", "high", "critical"]).optional(),
    priority: z5.enum(["low", "medium", "high", "urgent"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ project_id, title, description, severity, priority }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("defects").insert({ project_id, title, description, severity, priority, reported_by: ctx.getUserId(), status: "open" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created defect ${data.id}` }], structuredContent: { defect: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "seqnkjuoilkrrazvgoae";
var mcp_default = defineMcp({
  name: "qualixa-mcp",
  title: "Qualixa MCP",
  version: "0.1.0",
  instructions: "Tools for Qualixa, the AI-powered Quality Intelligence Platform. Use these to browse projects, test plans, test cases, and defects, and to file new defects on behalf of the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, list_test_plans_default, list_test_cases_default, list_defects_default, create_defect_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
